base_global_planner: SBPLLatticePlanner

SBPLLatticePlanner:
  environment_type: XYThetaLattice
#  planner_type: ARAPlanner
  allocated_time: 10.0
  initial_epsilon: 10.0
  forward_search: false
#  primitive_filename: /home/furkan/turtlebot3_melodic_ws/src/sbpl_lattice_planner/matlab/mprim/unicycle_5cm_expensive_turn_in_place_highcost.mprim
#  primitive_filename: /home/furkan/turtlebot3_melodic_ws/src/sbpl_lattice_planner/matlab/mprim/matlab_primitives/generated_primitives_16_10.mprim
#  primitive_filename: /home/furkan/turtlebot3_melodic_ws/src/sbpl_lattice_planner/matlab/mprim/python_motion_primitives/numberofangles_16_7.mprim

