components_configurations_folder: ~/turtlebot3_melodic_ws/src/global_planning_performance_modelling/config/component_configurations
#gazebo_model_path_env_var: [~/turtlebot3_melodic_ws/src/turtlebot3_simulations/turtlebot3_gazebo/models/]      #we are not using simulation   
#gazebo_plugin_path_env_var: [~/turtlebot3_melodic_ws/build/gazebo_plugins/]                                    #we are not using simulation
sbpl_primitives_path: ~/turtlebot3_melodic_ws/src/sbpl_lattice_planner/matlab/mprim/

supervisor_component: global_planning_benchmark_supervisor

components_configuration:
  supervisor: global_planning_benchmark_supervisor/global_planning_benchmark_supervisor.yaml
  move_base: move_base/move_base_tb3.yaml
  move_base_global_planner: move_base/move_base_sbpl_lattice_planner.yaml
  rviz: rviz/default_view.rviz

combinatorial_parameters:        #you can write your combinatory parameters here as an dict in grid_benchmarking.py is taking them
  global_planner_name: [SBPLLatticePlanner]
  sbpl_primitives_name: [unicycle_5cm_expensive_turn_in_place_highcost.mprim]
  planner_type: [ADplanner, ARAplanner]
