supervisor_component: localization_benchmark_supervisor
supervisor_configuration: localization_benchmark_supervisor/localization_benchmark_supervisor.yaml

components_configurations:
  nav2_amcl: [nav2_amcl/nav2_amcl_1.yaml]
  nav2_navigation: [nav2_navigation/nav2_navigation_1.yaml]